# Generated by Django 4.0.3 on 2024-07-23 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='push',
            field=models.CharField(choices=[('push-on', '通知する'), ('push-off', '通知しない')], default='push-off', max_length=20),
        ),
    ]
